'use strict';

/* ==========================================================================
   LISTA KOMPOZICIJA
   --------------------------------------------------------------------------
   Izvor: Kompozicije/Spisak kompozicija.md (beleške + „Kompozicije za 3. razred“).

   Svaki red je jedna kompozicija:

     { aktivna: true, kompozitor: "Ime", naslov: "Naziv dela", youtubeId: "xxxxxxxxxxx", start: 30 },

   - aktivna: true = ulazi u kviz, false = isključena (ostaje u listi, ne pojavljuje se
       ni kao pitanje ni kao ponuđeni odgovor).
   - youtubeId: 11 znakova iz YouTube linka.
       https://www.youtube.com/watch?v=SSypujlLlNI  ->  "SSypujlLlNI"
       https://youtu.be/SSypujlLlNI                 ->  "SSypujlLlNI"
   - start (opciono): od koje sekunde kreće klip. 1:30 = 90.
   - izgovor (opciono): šta glas tačno izgovara, ako se razlikuje od natpisa
       (npr. brojevi: "Peta simfonija").
   - audio (opciono): snimljena najava umesto sintetičkog glasa, putanja do mp3
       fajla: audio: "najave/SSypujlLlNI.mp3"
       Najave za kompozicije koje ih nemaju snima skripta (istim srpskim glasom):
         node alati/najave.mjs
       Ako nema najave, naziv čita glas pregledača.
   ========================================================================== */
const KOMPOZICIJE = [
  { aktivna: true, kompozitor: "Vivaldi", naslov: "Četiri godišnja doba, Proleće", youtubeId: "3LiztfE1X7E", start: 0,
    audio: "najave/3LiztfE1X7E.mp3" },
  { aktivna: true, kompozitor: "Vivaldi", naslov: "Četiri godišnja doba, Zima", youtubeId: "UWg5ugyMjIc", start: 0,
    audio: "najave/UWg5ugyMjIc.mp3" },
  { aktivna: true, kompozitor: "Bah", naslov: "Badineri", youtubeId: "gyMtlvOcojU", start: 0,
    audio: "najave/gyMtlvOcojU.mp3" },
  { aktivna: true, kompozitor: "Bah", naslov: "Tokata i fuga u de-molu", youtubeId: "8tpzyYFqJWM", start: 0,
    izgovor: "Bah. Tokata i fuga u de molu.",
    audio: "najave/8tpzyYFqJWM.mp3" },
  { aktivna: true, kompozitor: "Hendl", naslov: "Mesija, hor Aleluja", youtubeId: "IUZEtVbJT5c", start: 16,
    audio: "najave/IUZEtVbJT5c.mp3" },
  { aktivna: true, kompozitor: "Betoven", naslov: "Za Elizu", youtubeId: "q9bU12gXUyM", start: 0,
    audio: "najave/q9bU12gXUyM.mp3" },
  { aktivna: true, kompozitor: "Betoven", naslov: "5. simfonija (Sudbinska)", youtubeId: "SSypujlLlNI", start: 0,
    izgovor: "Betoven. Peta simfonija, Sudbinska.",
    audio: "najave/SSypujlLlNI.mp3" },
  { aktivna: true, kompozitor: "Betoven", naslov: "Mesečeva sonata", youtubeId: "nT7_IZPHHb0", start: 0,
    audio: "najave/nT7_IZPHHb0.mp3" },
  { aktivna: true, kompozitor: "Betoven", naslov: "9. simfonija, Oda radosti", youtubeId: "8RLPG88u3lM", start: 0,
    izgovor: "Betoven. Deveta simfonija, Oda radosti.",
    audio: "najave/8RLPG88u3lM.mp3" },
  { aktivna: true, kompozitor: "Mocart", naslov: "Mala noćna muzika", youtubeId: "UzEX0-nwN4Y", start: 0,
    audio: "najave/UzEX0-nwN4Y.mp3" },
  { aktivna: true, kompozitor: "Mocart", naslov: "Turski marš", youtubeId: "A_THdzBnHy0", start: 0,
    audio: "najave/A_THdzBnHy0.mp3" },
  { aktivna: true, kompozitor: "Mocart", naslov: "40. simfonija", youtubeId: "UEj6OJ4-4Bw", start: 0,
    izgovor: "Mocart. Četrdeseta simfonija.",
    audio: "najave/UEj6OJ4-4Bw.mp3" },
  { aktivna: true, kompozitor: "Mocart", naslov: "Rekvijem, Dan gneva", youtubeId: "RIIOzwz5bw0", start: 0,
    audio: "najave/RIIOzwz5bw0.mp3" },
  { aktivna: true, kompozitor: "Mocart", naslov: "Čarobna frula, arija Kraljice noći", youtubeId: "YuBeBjqKSGQ", start: 38,
    audio: "najave/YuBeBjqKSGQ.mp3" },
  { aktivna: true, kompozitor: "Albinoni", naslov: "Adađo", youtubeId: "XMbvcp480Y4", start: 20,
    audio: "najave/XMbvcp480Y4.mp3" },
  { aktivna: true, kompozitor: "Šuman", naslov: "Sanjarenje", youtubeId: "6z82w0l6kwE", start: 0,
    audio: "najave/6z82w0l6kwE.mp3" },
  { aktivna: true, kompozitor: "Šopen", naslov: "Revolucionarna etida", youtubeId: "g1uLrHq9TDg", start: 0,
    audio: "najave/g1uLrHq9TDg.mp3" },
  { aktivna: true, kompozitor: "Šopen", naslov: "Valcer u cis-molu", youtubeId: "WVsGf1ag6Us", start: 0,
    izgovor: "Šopen. Valcer u cis molu.",
    audio: "najave/WVsGf1ag6Us.mp3" },
  { aktivna: true, kompozitor: "Rosini", naslov: "Seviljski berberin, arija Figara", youtubeId: "-bhlWgyjEQs", start: 255,
    audio: "najave/-bhlWgyjEQs.mp3" },
  { aktivna: true, kompozitor: "Verdi", naslov: "Rigoleto, La donna è mobile", youtubeId: "xCFEk6Y8TmM", start: 0,
    izgovor: "Verdi. Rigoleto, La dona e mobile.",
    audio: "najave/xCFEk6Y8TmM.mp3" },
  { aktivna: true, kompozitor: "Bah", naslov: "Koncert za dve violine", youtubeId: "ILKJcsET-NM", start: 24,
    audio: "najave/ILKJcsET-NM.mp3" },
  { aktivna: true, kompozitor: "Mocart", naslov: "Figarova ženidba, uvertira", youtubeId: "ikQNFqVkNNc", start: 0,
    audio: "najave/ikQNFqVkNNc.mp3" },
  { aktivna: true, kompozitor: "Mocart", naslov: "Rekvijem, Lakrimoza", youtubeId: "MafAZeag1_0", start: 0,
    audio: "najave/MafAZeag1_0.mp3" },
  { aktivna: true, kompozitor: "Betoven", naslov: "Patetična sonata, 2. stav", youtubeId: "0njpfL1tXEg", start: 0,
    izgovor: "Betoven. Patetična sonata, drugi stav.",
    audio: "najave/0njpfL1tXEg.mp3" },
  { aktivna: true, kompozitor: "Mendelson", naslov: "Svadbeni marš", youtubeId: "0Oo4z37OUEI", start: 0,
    audio: "najave/0Oo4z37OUEI.mp3" },
  { aktivna: true, kompozitor: "Mendelson", naslov: "Koncert za violinu", youtubeId: "4YAeycqCgho", start: 0,
    audio: "najave/4YAeycqCgho.mp3" },
  { aktivna: true, kompozitor: "Verdi", naslov: "Nabuko, hor Jevreja", youtubeId: "aiSSz0snWzA", start: 72,
    audio: "najave/aiSSz0snWzA.mp3" },
  { aktivna: true, kompozitor: "Verdi", naslov: "Trubadur, hor Cigana", youtubeId: "UGtCTH2C8RE", start: 0,
    audio: "najave/UGtCTH2C8RE.mp3" },
  { aktivna: true, kompozitor: "Verdi", naslov: "Aida, Trijumfalni marš", youtubeId: "AssDQbaIP_I", start: 150,
    audio: "najave/AssDQbaIP_I.mp3" },
  { aktivna: true, kompozitor: "Verdi", naslov: "Travijata, Zdravica", youtubeId: "afhAqMeeQJk", start: 0,
    audio: "najave/afhAqMeeQJk.mp3" },
  { aktivna: true, kompozitor: "Grig", naslov: "Koncert za klavir", youtubeId: "vmUPl7Pv0Zg", start: 0,
    audio: "najave/vmUPl7Pv0Zg.mp3" },
  { aktivna: true, kompozitor: "Brams", naslov: "5. mađarska igra", youtubeId: "3X9LvC9WkkQ", start: 0,
    izgovor: "Brams. Peta mađarska igra.",
    audio: "najave/3X9LvC9WkkQ.mp3" },
  { aktivna: true, kompozitor: "Šopen", naslov: "Minutni valcer", youtubeId: "hKILwVH_MdM", start: 0,
    audio: "najave/hKILwVH_MdM.mp3" },
  { aktivna: true, kompozitor: "Delib", naslov: "Kopelija, valcer", youtubeId: "dixdXcZouZ8", start: 0,
    audio: "najave/dixdXcZouZ8.mp3" },
  { aktivna: true, kompozitor: "Delib", naslov: "Lakme, Duet cveća", youtubeId: "H_PZ6IBCof4", start: 100,
    audio: "najave/H_PZ6IBCof4.mp3" },
  { aktivna: true, kompozitor: "Berlioz", naslov: "Fantastična simfonija, Na balu", youtubeId: "IpW7c16eWeE", start: 36,
    audio: "najave/IpW7c16eWeE.mp3" },
  { aktivna: true, kompozitor: "Doniceti", naslov: "Ljubavni napitak, Una furtiva lagrima", youtubeId: "Hrh5oiy5kR8", start: 105,
    audio: "najave/Hrh5oiy5kR8.mp3" },
  { aktivna: true, kompozitor: "Belini", naslov: "Norma, Casta diva", youtubeId: "g-6JhBYZCrw", start: 78,
    izgovor: "Belini. Norma, Kasta diva.",
    audio: "najave/g-6JhBYZCrw.mp3" },
  { aktivna: true, kompozitor: "Mokranjac", naslov: "2. rukovet, Osu se nebo zvezdama", youtubeId: "NEEuh-HU9tM", start: 0,
    izgovor: "Mokranjac. Druga rukovet, Osu se nebo zvezdama.",
    audio: "najave/NEEuh-HU9tM.mp3" },
  { aktivna: true, kompozitor: "Šubert", naslov: "5. simfonija, 1. stav", youtubeId: "Fl3imP3zenE", start: 0,
    izgovor: "Šubert. Peta simfonija, prvi stav.",
    audio: "najave/Fl3imP3zenE.mp3" },
  { aktivna: true, kompozitor: "Šubert", naslov: "Ave Marija", youtubeId: "ja5hQH9USIU", start: 0,
    audio: "najave/ja5hQH9USIU.mp3" },
  { aktivna: true, kompozitor: "Maskanji", naslov: "Kavalerija rustikana, Intermeco", youtubeId: "-fDTjTzB0Gc", start: 180,
    audio: "najave/-fDTjTzB0Gc.mp3" },
  { aktivna: true, kompozitor: "Leonkavalo", naslov: "Pajaci, Smej se, Pajaco", youtubeId: "Z0PMq4XGtZ4", start: 114,
    audio: "najave/Z0PMq4XGtZ4.mp3" },
  { aktivna: true, kompozitor: "Pučini", naslov: "Toska, Zvezde su sjale", youtubeId: "5-AF1T4OehM", start: 0,
    audio: "najave/5-AF1T4OehM.mp3" },
  { aktivna: true, kompozitor: "Pučini", naslov: "Turandot, Niko ne spava", youtubeId: "2RdJmqLrsbo", start: 0,
    audio: "najave/2RdJmqLrsbo.mp3" },
  { aktivna: true, kompozitor: "Borodin", naslov: "Knez Igor, Polovecke igre", youtubeId: "wiexn6O9To4", start: 74,
    audio: "najave/wiexn6O9To4.mp3" },
  { aktivna: true, kompozitor: "Rimski-Korsakov", naslov: "Bumbarov let", youtubeId: "aYAJopwEYv8", start: 0,
    audio: "najave/aYAJopwEYv8.mp3" },
  { aktivna: true, kompozitor: "Musorgski", naslov: "Slike sa izložbe, Promenada", youtubeId: "13sQ77jB3bs", start: 0,
    audio: "najave/13sQ77jB3bs.mp3" },
  { aktivna: true, kompozitor: "Musorgski", naslov: "Noć na golom brdu", youtubeId: "iCEDfZgDPS8", start: 0,
    audio: "najave/iCEDfZgDPS8.mp3" },
  { aktivna: true, kompozitor: "Čajkovski", naslov: "Krcko Oraščić, Valcer cveća", youtubeId: "Zp1aDnVySf8", start: 100,
    audio: "najave/Zp1aDnVySf8.mp3" },
  { aktivna: true, kompozitor: "Čajkovski", naslov: "Labudovo jezero, lajtmotiv bele labudice", youtubeId: "HnQku3z-Rok", start: 0,
    audio: "najave/HnQku3z-Rok.mp3" },
  { aktivna: true, kompozitor: "Čajkovski", naslov: "Labudovo jezero, Igra malih labudova", youtubeId: "0GsajWIF3ws", start: 0,
    audio: "najave/0GsajWIF3ws.mp3" },
  { aktivna: true, kompozitor: "Čajkovski", naslov: "Uspavana lepotica, Valcer", youtubeId: "2Sb8WCPjPDs", start: 33,
    audio: "najave/2Sb8WCPjPDs.mp3" },
  { aktivna: true, kompozitor: "Čajkovski", naslov: "Koncert za klavir br. 1", youtubeId: "YmYeISiVPOw", start: 0,
    audio: "najave/YmYeISiVPOw.mp3" },
  { aktivna: true, kompozitor: "Čajkovski", naslov: "Uvertira 1812", youtubeId: "WtVTkieODaw", start: 155,
    izgovor: "Čajkovski. Uvertira osamnaest dvanaest.",
    audio: "najave/WtVTkieODaw.mp3" },
  { aktivna: true, kompozitor: "Čajkovski", naslov: "Slovenski marš", youtubeId: "5poSw7tFLB4", start: 0,
    audio: "najave/5poSw7tFLB4.mp3" },
  { aktivna: true, kompozitor: "Smetana", naslov: "Moja domovina, Vltava", youtubeId: "JcDzRjMIDvo", start: 0,
    audio: "najave/JcDzRjMIDvo.mp3" },
  { aktivna: true, kompozitor: "Dvoržak", naslov: "Simfonija Iz Novog sveta, 4. stav", youtubeId: "jVDofBFtvwA", start: 0,
    izgovor: "Dvoržak. Simfonija Iz Novog sveta, četvrti stav.",
    audio: "najave/jVDofBFtvwA.mp3" },
  { aktivna: true, kompozitor: "Dvoržak", naslov: "Slovenska igra br. 8", youtubeId: "WIywT8fKVZA", start: 0,
    audio: "najave/WIywT8fKVZA.mp3" },
  { aktivna: true, kompozitor: "Mokranjac", naslov: "10. rukovet, Biljana platno beleše", youtubeId: "yjPL-Q7-_ZI", start: 0,
    izgovor: "Mokranjac. Deseta rukovet, Biljana platno beleše.",
    audio: "najave/yjPL-Q7-_ZI.mp3" },
  { aktivna: true, kompozitor: "Mokranjac", naslov: "Heruvimska pesma", youtubeId: "iYVEuGzrNLA", start: 0,
    audio: "najave/iYVEuGzrNLA.mp3" },
];
